Global:
    text_score: 0.5
    use_det: true
    use_cls: true
    use_rec: true
    print_verbose: false
    min_height: 30
    width_height_ratio: 8

Det:
    use_cuda: false
    num_threads: 1
    execution_mode: 1  # <ExecutionMode.ORT_PARALLEL: 1> <ExecutionMode.ORT_SEQUENTIAL: 0>
    model_path: data/ocr/ch/det/ch_PP-OCRv3_det_infer.onnx
    limit_side_len: 960
    limit_type: max
    thresh: 0.3
    box_thresh: 0.5
    max_candidates: 1000
    unclip_ratio: 1.6
    use_dilation: true
    score_mode: fast

Cls:
    use_cuda: false
    num_threads: 1
    execution_mode: 1  # <ExecutionMode.ORT_PARALLEL: 1> <ExecutionMode.ORT_SEQUENTIAL: 0>
    model_path: data/ocr/ch/cls/ch_ppocr_mobile_v2.0_cls_infer.onnx
    cls_image_shape: [3, 48, 192]
    cls_batch_num: 6
    cls_thresh: 0.9
    label_list: ['0', '180']

Rec:
    use_cuda: false
    num_threads: 1
    execution_mode: 1  # <ExecutionMode.ORT_PARALLEL: 1> <ExecutionMode.ORT_SEQUENTIAL: 0>
    model_path: data/ocr/ch/rec/ch_ppocr_mobile_v2.0_rec_infer.onnx
    rec_img_shape: [3, 32, 320]
    rec_batch_num: 6
